// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/projects/[projectId]": InferRoute<import("./app/(app)/projects/[projectId]/(projectId)/route-type").RouteType>;
    "/projects/[projectId]/features": InferRoute<import("./app/(app)/projects/[projectId]/features/route-type").RouteType>;
    "/projects/[projectId]/features/[featureId]": InferRoute<import("./app/(app)/projects/[projectId]/features/[featureId]/route-type").RouteType>;
    "/projects/[projectId]/repositories": InferRoute<import("./app/(app)/projects/[projectId]/repositories/route-type").RouteType>;
    "/projects/[projectId]/settings": InferRoute<import("./app/(app)/projects/[projectId]/settings/route-type").RouteType>;
    "/projects/[projectId]/usage": InferRoute<import("./app/(app)/projects/[projectId]/usage/route-type").RouteType>;
  }

  interface StaticRouter {
    "/help": StaticRoute;
    "/": StaticRoute;
    "/projects": StaticRoute;
    "/settings": StaticRoute;
  }
}
