import { z } from 'zod';

// Status enum for clarification workflow stages
export const clarificationStatusSchema = z.enum(['analyzing', 'completed', 'idle', 'questions_ready', 'skipped']);

export type ClarificationStatus = z.infer<typeof clarificationStatusSchema>;

// Option for a clarifying question
export const clarificationOptionSchema = z.object({
  description: z.string().optional(),
  label: z.string(),
  value: z.string(),
});

export type ClarificationOption = z.infer<typeof clarificationOptionSchema>;

// A single clarifying question generated by AI
export const clarificationQuestionSchema = z.object({
  allowCustom: z.boolean().default(true),
  id: z.string(),
  options: z.array(clarificationOptionSchema),
  question: z.string(),
});

export type ClarificationQuestion = z.infer<typeof clarificationQuestionSchema>;

// Array of questions
export const clarificationQuestionsSchema = z.array(clarificationQuestionSchema);

export type ClarificationQuestions = z.infer<typeof clarificationQuestionsSchema>;

// User's answer to a clarifying question
export const clarificationAnswerSchema = z.object({
  customText: z.string().optional(),
  questionId: z.string(),
  selectedValue: z.string().nullable(),
});

export type ClarificationAnswer = z.infer<typeof clarificationAnswerSchema>;

// Array of answers
export const clarificationAnswersSchema = z.array(clarificationAnswerSchema);

export type ClarificationAnswers = z.infer<typeof clarificationAnswersSchema>;

// AI analysis findings structure
export const clarificationAnalysisSchema = z.object({
  affectedAreas: z.array(z.string()).optional(),
  ambiguities: z.array(z.string()).optional(),
  completedAt: z.string().optional(),
  detailScore: z.number().min(1).max(5),
  reasoning: z.string().optional(),
  summary: z.string(),
});

export type ClarificationAnalysis = z.infer<typeof clarificationAnalysisSchema>;

export function parseClarificationAnalysis(json: null | string | undefined): ClarificationAnalysis | null {
  if (!json) return null;
  try {
    const parsed = JSON.parse(json);
    return clarificationAnalysisSchema.parse(parsed);
  } catch {
    return null;
  }
}

export function parseClarificationAnswers(json: null | string | undefined): ClarificationAnswers {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return clarificationAnswersSchema.parse(parsed);
  } catch {
    return [];
  }
}

// Helper to parse JSON strings from database
export function parseClarificationQuestions(json: null | string | undefined): ClarificationQuestions {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return clarificationQuestionsSchema.parse(parsed);
  } catch {
    return [];
  }
}

export function parseClarificationStatus(status: null | string | undefined): ClarificationStatus {
  if (!status) return 'idle';
  const result = clarificationStatusSchema.safeParse(status);
  return result.success ? result.data : 'idle';
}

export function stringifyClarificationAnalysis(analysis: ClarificationAnalysis): string {
  return JSON.stringify(analysis);
}

export function stringifyClarificationAnswers(answers: ClarificationAnswers): string {
  return JSON.stringify(answers);
}

// Stringify helpers for saving to database
export function stringifyClarificationQuestions(questions: ClarificationQuestions): string {
  return JSON.stringify(questions);
}
