import { z } from 'zod';

// Status enum for clarification workflow stages
// - 'idle': Initial state, not started
// - 'analyzing': AI is analyzing the request
// - 'questions_ready': AI generated questions for user
// - 'completed': User answered questions and saved
// - 'skipped': AI determined request is detailed enough (high detail score)
// - 'skipped_by_user': User explicitly chose to skip clarification
export const clarificationStatusSchema = z.enum([
  'analyzing',
  'completed',
  'idle',
  'questions_ready',
  'skipped',
  'skipped_by_user',
]);

export type ClarificationStatus = z.infer<typeof clarificationStatusSchema>;

// Option for a clarifying question
export const clarificationOptionSchema = z.object({
  description: z.string().optional(),
  label: z.string(),
  value: z.string(),
});

export type ClarificationOption = z.infer<typeof clarificationOptionSchema>;

// A single clarifying question generated by AI
export const clarificationQuestionSchema = z.object({
  allowCustom: z.boolean().default(true),
  id: z.string(),
  options: z.array(clarificationOptionSchema),
  question: z.string(),
});

export type ClarificationQuestion = z.infer<typeof clarificationQuestionSchema>;

// Array of questions
export const clarificationQuestionsSchema = z.array(clarificationQuestionSchema);

export type ClarificationQuestions = z.infer<typeof clarificationQuestionsSchema>;

// User's answer to a clarifying question
export const clarificationAnswerSchema = z.object({
  customText: z.string().optional(),
  questionId: z.string(),
  selectedValue: z.string().nullable(),
});

export type ClarificationAnswer = z.infer<typeof clarificationAnswerSchema>;

// Array of answers
export const clarificationAnswersSchema = z.array(clarificationAnswerSchema);

export type ClarificationAnswers = z.infer<typeof clarificationAnswersSchema>;

// AI analysis findings structure
export const clarificationAnalysisSchema = z.object({
  affectedAreas: z.array(z.string()).optional(),
  ambiguities: z.array(z.string()).optional(),
  completedAt: z.string().optional(),
  detailScore: z.number().min(1).max(5),
  reasoning: z.string().optional(),
  summary: z.string(),
});

export type ClarificationAnalysis = z.infer<typeof clarificationAnalysisSchema>;

// Parse result type for functions that need error information
export interface ParseResult<T> {
  data: T;
  error: null | string;
}

export function parseClarificationAnalysis(json: null | string | undefined): ClarificationAnalysis | null {
  if (!json) return null;
  try {
    const parsed = JSON.parse(json);
    return clarificationAnalysisSchema.parse(parsed);
  } catch {
    return null;
  }
}

/**
 * Parse clarification analysis with error reporting.
 * Returns both the parsed data (or null) and any error that occurred.
 */
export function parseClarificationAnalysisWithError(
  json: null | string | undefined
): ParseResult<ClarificationAnalysis | null> {
  if (!json) return { data: null, error: null };
  try {
    const parsed = JSON.parse(json);
    return { data: clarificationAnalysisSchema.parse(parsed), error: null };
  } catch (e) {
    return {
      data: null,
      error: `Failed to parse clarification analysis: ${e instanceof Error ? e.message : 'Invalid JSON'}`,
    };
  }
}

export function parseClarificationAnswers(json: null | string | undefined): ClarificationAnswers {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return clarificationAnswersSchema.parse(parsed);
  } catch {
    return [];
  }
}

/**
 * Parse clarification answers with error reporting.
 * Returns both the parsed data (empty array fallback) and any error that occurred.
 */
export function parseClarificationAnswersWithError(json: null | string | undefined): ParseResult<ClarificationAnswers> {
  if (!json) return { data: [], error: null };
  try {
    const parsed = JSON.parse(json);
    return { data: clarificationAnswersSchema.parse(parsed), error: null };
  } catch (e) {
    return {
      data: [],
      error: `Failed to parse clarification answers: ${e instanceof Error ? e.message : 'Invalid JSON'}`,
    };
  }
}

// Helper to parse JSON strings from database
export function parseClarificationQuestions(json: null | string | undefined): ClarificationQuestions {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return clarificationQuestionsSchema.parse(parsed);
  } catch {
    return [];
  }
}

/**
 * Parse clarification questions with error reporting.
 * Returns both the parsed data (empty array fallback) and any error that occurred.
 */
export function parseClarificationQuestionsWithError(
  json: null | string | undefined
): ParseResult<ClarificationQuestions> {
  if (!json) return { data: [], error: null };
  try {
    const parsed = JSON.parse(json);
    return { data: clarificationQuestionsSchema.parse(parsed), error: null };
  } catch (e) {
    return {
      data: [],
      error: `Failed to parse clarification questions: ${e instanceof Error ? e.message : 'Invalid JSON'}`,
    };
  }
}

export function parseClarificationStatus(status: null | string | undefined): ClarificationStatus {
  if (!status) return 'idle';
  const result = clarificationStatusSchema.safeParse(status);
  return result.success ? result.data : 'idle';
}

/**
 * Parse run outputContent JSON with error reporting.
 * Returns structured data and any parse error.
 */
export function parseRunOutputContent(outputContent: null | string | undefined): {
  analysis: ClarificationAnalysis | null;
  answers: ClarificationAnswers;
  error: null | string;
  questions: ClarificationQuestions;
} {
  if (!outputContent) {
    return { analysis: null, answers: [], error: null, questions: [] };
  }

  try {
    const parsed = JSON.parse(outputContent) as {
      analysis?: unknown;
      answers?: unknown;
      questions?: unknown;
    };

    const errors: Array<string> = [];

    // Parse analysis
    let analysis: ClarificationAnalysis | null = null;
    if (parsed.analysis) {
      const result = clarificationAnalysisSchema.safeParse(parsed.analysis);
      if (result.success) {
        analysis = result.data;
      } else {
        errors.push('Invalid analysis data');
      }
    }

    // Parse questions
    let questions: ClarificationQuestions = [];
    if (parsed.questions) {
      const result = clarificationQuestionsSchema.safeParse(parsed.questions);
      if (result.success) {
        questions = result.data;
      } else {
        errors.push('Invalid questions data');
      }
    }

    // Parse answers
    let answers: ClarificationAnswers = [];
    if (parsed.answers) {
      const result = clarificationAnswersSchema.safeParse(parsed.answers);
      if (result.success) {
        answers = result.data;
      } else {
        errors.push('Invalid answers data');
      }
    }

    return {
      analysis,
      answers,
      error: errors.length > 0 ? `Run data corrupted: ${errors.join(', ')}` : null,
      questions,
    };
  } catch (e) {
    return {
      analysis: null,
      answers: [],
      error: `Failed to parse run output: ${e instanceof Error ? e.message : 'Invalid JSON'}`,
      questions: [],
    };
  }
}

export function stringifyClarificationAnalysis(analysis: ClarificationAnalysis): string {
  return JSON.stringify(analysis);
}

export function stringifyClarificationAnswers(answers: ClarificationAnswers): string {
  return JSON.stringify(answers);
}

// Stringify helpers for saving to database
export function stringifyClarificationQuestions(questions: ClarificationQuestions): string {
  return JSON.stringify(questions);
}
