import { z } from 'zod';

// Status enum for plan workflow stages
// - 'idle': Initial state, not started
// - 'generating': AI is generating the implementation plan
// - 'completed': Plan generation finished successfully
// - 'failed': Plan generation encountered an error
export const planStatusSchema = z.enum(['completed', 'failed', 'generating', 'idle']);

export type PlanStatus = z.infer<typeof planStatusSchema>;

// Complexity level for plan steps
export const planStepComplexitySchema = z.enum(['high', 'low', 'medium']);

export type PlanStepComplexity = z.infer<typeof planStepComplexitySchema>;

// Quality gate type for validation checkpoints
// - 'command': Automated validation via command execution
// - 'manual': Manual verification by the user
export const qualityGateTypeSchema = z.enum(['command', 'manual']);

export type QualityGateType = z.infer<typeof qualityGateTypeSchema>;

// A quality gate for validating implementation steps
export const qualityGateSchema = z.object({
  command: z.string().optional(),
  description: z.string(),
  type: qualityGateTypeSchema,
});

export type QualityGate = z.infer<typeof qualityGateSchema>;

// Array of quality gates
export const qualityGatesSchema = z.array(qualityGateSchema);

export type QualityGates = z.infer<typeof qualityGatesSchema>;

// A file affected by a plan step
export const planFileSchema = z.object({
  action: z.enum(['create', 'delete', 'modify', 'review']).optional(),
  path: z.string(),
  reason: z.string().optional(),
});

export type PlanFile = z.infer<typeof planFileSchema>;

// Array of plan files
export const planFilesSchema = z.array(planFileSchema);

export type PlanFiles = z.infer<typeof planFilesSchema>;

// A single step in the implementation plan
export const planStepSchema = z.object({
  complexity: planStepComplexitySchema,
  description: z.string(),
  files: planFilesSchema,
  order: z.number().int().positive(),
  qualityGates: qualityGatesSchema.optional(),
  title: z.string(),
});

export type PlanStep = z.infer<typeof planStepSchema>;

// Array of plan steps
export const planStepsSchema = z.array(planStepSchema);

export type PlanSteps = z.infer<typeof planStepsSchema>;

// Risk entry for the implementation plan
export const planRiskSchema = z.object({
  description: z.string(),
  level: z.enum(['high', 'low', 'medium']).optional(),
  mitigation: z.string().optional(),
});

export type PlanRisk = z.infer<typeof planRiskSchema>;

// Array of plan risks
export const planRisksSchema = z.array(planRiskSchema);

export type PlanRisks = z.infer<typeof planRisksSchema>;

// Testing strategy for the implementation plan
export const testingStrategySchema = z.object({
  commands: z.array(z.string()).optional(),
  description: z.string(),
  unitTests: z.array(z.string()).optional(),
});

export type TestingStrategy = z.infer<typeof testingStrategySchema>;

// Complete implementation plan generated by AI
export const implementationPlanSchema = z.object({
  completedAt: z.string().optional(),
  confidence: z.number().min(0).max(100).optional(),
  modelUsed: z.string().optional(),
  overview: z.string(),
  prerequisites: z.array(z.string()).optional(),
  reasoning: z.string().optional(),
  risks: planRisksSchema.optional(),
  steps: planStepsSchema,
  summary: z.string(),
  testingStrategy: testingStrategySchema.optional(),
  timestamp: z.string().optional(),
});

export type ImplementationPlan = z.infer<typeof implementationPlanSchema>;

// Parse implementation plan from JSON string (used when reading from database)
export function parseImplementationPlan(json: null | string | undefined): ImplementationPlan | null {
  if (!json) return null;
  try {
    const parsed = JSON.parse(json);
    return implementationPlanSchema.parse(parsed);
  } catch {
    return null;
  }
}

// Parse plan status from string (used when reading from database)
export function parsePlanStatus(status: null | string | undefined): PlanStatus {
  if (!status) return 'idle';
  const result = planStatusSchema.safeParse(status);
  return result.success ? result.data : 'idle';
}

// Parse plan steps from JSON string (used when reading from database)
export function parsePlanSteps(json: null | string | undefined): PlanSteps {
  if (!json) return [];
  try {
    const parsed: unknown = JSON.parse(json);

    // Handle object format (ImplementationPlan with steps property)
    if (parsed && typeof parsed === 'object' && 'steps' in parsed) {
      const obj = parsed as { steps: unknown };
      if (Array.isArray(obj.steps)) {
        return planStepsSchema.parse(obj.steps);
      }
    }

    // Handle direct array format
    return planStepsSchema.parse(parsed);
  } catch {
    return [];
  }
}

// Parse quality gates from JSON string
export function parseQualityGates(json: null | string | undefined): QualityGates {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return qualityGatesSchema.parse(parsed);
  } catch {
    return [];
  }
}

// Stringify implementation plan for database storage
export function stringifyImplementationPlan(plan: ImplementationPlan): string {
  return JSON.stringify(plan);
}

// Stringify plan steps for database storage
export function stringifyPlanSteps(steps: PlanSteps): string {
  return JSON.stringify(steps);
}

// Stringify quality gates for database storage
export function stringifyQualityGates(gates: QualityGates): string {
  return JSON.stringify(gates);
}
