export const IpcChannels = {
  ai: {
    aiDiscovery: {
      cancel: 'ai:aiDiscovery:cancel',
      generate: 'ai:aiDiscovery:generate',
      stream: 'ai:aiDiscovery:stream',
    },
    clarification: {
      cancel: 'ai:clarification:cancel',
      generate: 'ai:clarification:generate',
      stream: 'ai:clarification:stream',
    },
    discovery: {
      cancel: 'ai:discovery:cancel',
      generate: 'ai:discovery:generate',
      stream: 'ai:discovery:stream',
    },
    plan: {
      cancel: 'ai:plan:cancel',
      generate: 'ai:plan:generate',
      stream: 'ai:plan:stream',
    },
    repositoryOverview: {
      cancel: 'ai:repositoryOverview:cancel',
      generate: 'ai:repositoryOverview:generate',
      stream: 'ai:repositoryOverview:stream',
    },
  },
  apiKeys: {
    delete: 'apiKeys:delete',
    get: 'apiKeys:get',
    getAll: 'apiKeys:getAll',
    isEncryptionAvailable: 'apiKeys:isEncryptionAvailable',
    set: 'apiKeys:set',
    test: 'apiKeys:test',
    toggleDisabled: 'apiKeys:toggleDisabled',
  },
  app: {
    getPath: 'app:getPath',
    getVersion: 'app:getVersion',
  },
  db: {
    featureRequestContextFiles: {
      bulkCreate: 'db:featureRequestContextFiles:bulkCreate',
      create: 'db:featureRequestContextFiles:create',
      delete: 'db:featureRequestContextFiles:delete',
      getByFeatureRequestId: 'db:featureRequestContextFiles:getByFeatureRequestId',
      getByFeatureRequestIdAndType: 'db:featureRequestContextFiles:getByFeatureRequestIdAndType',
      getById: 'db:featureRequestContextFiles:getById',
      setIncludedInContext: 'db:featureRequestContextFiles:setIncludedInContext',
      update: 'db:featureRequestContextFiles:update',
    },
    featureRequestRepositories: {
      addToFeatureRequest: 'db:featureRequestRepositories:addToFeatureRequest',
      getByFeatureRequestId: 'db:featureRequestRepositories:getByFeatureRequestId',
      removeFromFeatureRequest: 'db:featureRequestRepositories:removeFromFeatureRequest',
      setForFeatureRequest: 'db:featureRequestRepositories:setForFeatureRequest',
    },
    featureRequestRuns: {
      create: 'db:featureRequestRuns:create',
      delete: 'db:featureRequestRuns:delete',
      getByFeatureRequestId: 'db:featureRequestRuns:getByFeatureRequestId',
      getByFeatureRequestIdAndStatus: 'db:featureRequestRuns:getByFeatureRequestIdAndStatus',
      getByFeatureRequestIdAndStep: 'db:featureRequestRuns:getByFeatureRequestIdAndStep',
      getById: 'db:featureRequestRuns:getById',
      getCurrentRun: 'db:featureRequestRuns:getCurrentRun',
      getLatestByFeatureRequestId: 'db:featureRequestRuns:getLatestByFeatureRequestId',
      getLatestByFeatureRequestIdAndStep: 'db:featureRequestRuns:getLatestByFeatureRequestIdAndStep',
      setCurrentRun: 'db:featureRequestRuns:setCurrentRun',
      update: 'db:featureRequestRuns:update',
    },
    featureRequests: {
      create: 'db:featureRequests:create',
      delete: 'db:featureRequests:delete',
      getById: 'db:featureRequests:getById',
      getByProjectId: 'db:featureRequests:getByProjectId',
      update: 'db:featureRequests:update',
    },
    projects: {
      create: 'db:projects:create',
      delete: 'db:projects:delete',
      getAll: 'db:projects:getAll',
      getById: 'db:projects:getById',
      getFavorited: 'db:projects:getFavorited',
      update: 'db:projects:update',
    },
    repositories: {
      create: 'db:repositories:create',
      delete: 'db:repositories:delete',
      getById: 'db:repositories:getById',
      getByProjectId: 'db:repositories:getByProjectId',
      update: 'db:repositories:update',
    },
    repositoryOverviews: {
      create: 'db:repositoryOverviews:create',
      delete: 'db:repositoryOverviews:delete',
      deleteByRepositoryId: 'db:repositoryOverviews:deleteByRepositoryId',
      getByRepositoryId: 'db:repositoryOverviews:getByRepositoryId',
      update: 'db:repositoryOverviews:update',
      upsert: 'db:repositoryOverviews:upsert',
    },
    stepConfigurations: {
      create: 'db:stepConfigurations:create',
      delete: 'db:stepConfigurations:delete',
      getById: 'db:stepConfigurations:getById',
      getByProjectId: 'db:stepConfigurations:getByProjectId',
      getByProjectIdAndStep: 'db:stepConfigurations:getByProjectIdAndStep',
      update: 'db:stepConfigurations:update',
      upsert: 'db:stepConfigurations:upsert',
    },
  },
  dialog: {
    openDirectory: 'dialog:openDirectory',
    openFile: 'dialog:openFile',
    saveFile: 'dialog:saveFile',
  },
  electron: {
    importRepositoryOverview: 'electron:importRepositoryOverview',
  },
  fileSearch: {
    cancel: 'fileSearch:cancel',
    progress: 'fileSearch:progress',
    search: 'fileSearch:search',
  },
  fs: {
    collectRepositoryData: 'fs:collectRepositoryData',
    exists: 'fs:exists',
    mkdir: 'fs:mkdir',
    readDirectory: 'fs:readDirectory',
    readFile: 'fs:readFile',
    stat: 'fs:stat',
    writeFile: 'fs:writeFile',
  },
  openRouterModels: {
    clear: 'openRouterModels:clear',
    fetch: 'openRouterModels:fetch',
    get: 'openRouterModels:get',
  },
  store: {
    delete: 'store:delete',
    get: 'store:get',
    set: 'store:set',
  },
} as const;
